
version: '3.8'  # Используйте последнюю поддерживаемую версию
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
  
    volumes:
      - .:/app
      - ./data:/app/data 
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      # - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - redis
      # - elasticsearch
    env_file:
      - .env
    
    db:
      image: sqlite
      volumes:
        - ./db.sqlite3:/app/db.sqlite3  # Привязываем базу данных

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - mynetwork
  
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m 
  #   ports:
  #     - "9200:9200"
    
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data

volumes:
  web:

networks:
  mynetwork:
    driver: bridge
  shared_network:
    external: true