# version: '26.1.1'

# services:
#   web:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     environment:
#       - DEBUG=True
#     depends_on:
#       - redis
#       - elasticsearch
#     env_file:
#       - .env
    
      

#   redis:
#     image: "redis:alpine"
#     ports:
#       - "6379:6379"
  
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
#     environment:
#       - discovery.type=single-node
#       - ES_JAVA_OPTS=-Xms512m -Xmx512m 
#     ports:
#       - "9200:9200"


version: '3.8'  # Используйте последнюю поддерживаемую версию
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    # command: bash -c "sleep 10 && python manage.py search_index --create && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - redis
      - elasticsearch
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m 
    ports:
      - "9200:9200"
    
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: