# Generated by Django 5.0.7 on 2024-07-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.publicationtype'),
        ),
    ]
