# Generated by Django 5.0.7 on 2024-09-13 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_tablemodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.RemoveField(
            model_name='tablemodel',
            name='Co_authors',
        ),
        migrations.CreateModel(
            name='TableModelAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.author')),
                ('table_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.tablemodel')),
            ],
            options={
                'verbose_name': 'Запись-Автор',
                'verbose_name_plural': 'Записи-Авторы',
            },
        ),
        migrations.AddField(
            model_name='tablemodel',
            name='authors',
            field=models.ManyToManyField(blank=True, through='table.TableModelAuthor', to='table.author'),
        ),
    ]
