# Generated by Django 5.0.7 on 2024-09-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_author_remove_tablemodel_co_authors_tablemodelauthor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemodel',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='tablemodelauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tablemodelauthor',
            name='table_model',
        ),
        migrations.AddField(
            model_name='tablemodel',
            name='authors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='TableModelAuthor',
        ),
    ]
