# Generated by Django 5.0.7 on 2024-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_remove_tablemodel_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='authors',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
